// @generated by site-forge — do not edit. Run `pnpm site sync` to regenerate.
// Add variables to a fragment in src/env/ instead; each module owns one.
import { createEnv } from "@t3-oss/env-nextjs";

import { adminEnv } from "./env/admin";
import { analyticsEnv } from "./env/analytics";
import { authEnv } from "./env/auth";
import { contactEnv } from "./env/contact";
import { coreEnv } from "./env/core";
import { databaseEnv } from "./env/database";
import { emailEnv } from "./env/email";
import { paymentsEnv } from "./env/payments";
import { rateLimitEnv } from "./env/rate-limit";

export const env = createEnv({
  extends: [
    coreEnv,
    analyticsEnv,
    emailEnv,
    rateLimitEnv,
    contactEnv,
    databaseEnv,
    authEnv,
    paymentsEnv,
    adminEnv,
  ],
  server: {},
  client: {},
  experimental__runtimeEnv: {},
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
